### ISSUE TITLE
The state of cDiep

### ISSUE THREAD

**Issue by haykam821** [SM-Wistful/cdiep#2]
Hello, Nylon. Your account seems pretty inactive and I wanted to know whether you were still working on cDiep. I have updated it so it works much better now, and wanted to upload it to GitHub under my own license.

~~If you don't respond within 2 weeks I'll assume you're dead and never coming back~~, but if you had any other ideas on what to do, I'm open to them as well.

**Edit:** I'm going to upload my changes to CommunityDiep/server, unless you have anything against that and I would take it down.

**Comment by SM-Wistful** [comment]
Hey! Feel free to make whatever changes you want to cDiep; it's as much yours and Koulatko's as it is mine. I'll try to communicate with your on Discord at some point this week so we can discuss this more and perhaps work together.

**Comment by SM-Wistful** [comment]
Sorry about the confusion -- I'm going to close this now. The issue seems to be resolved.
